version: '3'

services:
  backend:
    build: ./backend
    container_name: windows-sleep-backend
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - WINDOWS_PC_MAC=${WINDOWS_PC_MAC}
      - WINDOWS_PC_IP=${WINDOWS_PC_IP}
    cap_add:
      - NET_RAW
    networks:
      - app-network
    # ヘルスチェックを追加
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  frontend:
    build: ./frontend
    container_name: windows-sleep-frontend
    restart: always
    ports:
      - "3002:80"
    depends_on:
      backend:
        condition: service_healthy
    environment:
      - BACKEND_URL=http://backend:8000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
