version: '3'

services:
  backend:
    build: ./backend
    container_name: windows-sleep-backend
    restart: always
    ports:
      - "9876:8000"
    volumes:
      - ./backend:/app
    environment:
      - WINDOWS_PC_MAC=${WINDOWS_PC_MAC}
      - WINDOWS_PC_IP=${WINDOWS_PC_IP}
    cap_add:
      - NET_RAW
    networks:
      - app-network
    # ヘルスチェックを修正
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import socket; s = socket.socket(socket.AF_INET, socket.SOCK_STREAM); s.connect(('localhost', 8000)) or exit(1); s.close()\""]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  frontend:
    build: ./frontend
    container_name: windows-sleep-frontend
    restart: always
    ports:
      - "8765:80"
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:8000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
